### ISSUE TITLE
Fix compile time issues

### ISSUE THREAD

**Issue by TNychka** [X2LongWarOfTheChosen/LWOTC_Toolbox#2]
The current repository is nothing but the X2 base game code. It is completely unmodified from the PI release. There will be a significant number of issues in compiling this due to the WOTC refactoring of the base game code. Whoever takes this issue is free to either complete it by themselves or to break it down into smaller issues for other devs to handle.

**Comment by TNychka** [comment]
test

**Comment by Pete-Hamlin** [comment]
I'll start having a go at this one then
